### ISSUE TITLE
Error on Adding User's tags

### ISSUE THREAD

**Issue by cobisja** [rtconner/laravel-tagging#100]
Hi,

First of all, thanks for this amazing package.

I've been using the package with no problem but when I decided to make Laravel's User model into taggable using the Taggable trait, I have an error when I try to add a tag for a user instance:

` 
$user = User::first();
$user->tag('vip');
`

The last sentence above throws the following error:

`
Call to a member function makeTagArray() on null
`

I cannot understand why this error is happening. Others models I'm using with taggable trait work as expected.

Could you tell me what I'm doing wrong?

**Comment by cobisja** [comment]
Found the problem. My User model has defined a callback for created event through overridden boot method. The problem was I forgot to call parent boot method to Boot all of the bootable traits on the model.

Thanks again for your contribution.

**Comment by rtconner** [comment]
Lol OK good. I was as confused as you trying to figure out why that would happen.
