### ISSUE TITLE
artisan command group

### ISSUE THREAD

**Issue by struyfv** [rtconner/laravel-tagging#108]
When I run php artisan tagging:create-group MyTagGroup a get the following error: 

There are no commands defined in the "tagging" namespace.

Any ideas?

Thanks!

**Comment by LiYiBin** [comment]
@struyfv 
Did you install 2.1 version?
I saw the command code in dev-laravel-5 version.
Maybe it's not finished?

**Comment by rtconner** [comment]
Yeah use dev-laravel-5 until I can get that HHVM issue fixed.

**Comment by struyfv** [comment]
Yes I ran composer require rtconner/laravel-tagging "~2.1".
I solved it by downloading the zip.

**Comment by rtconner** [comment]
@struyfv use `"rtconner/laravel-tagging" : "dev-laravel-5"`
