### ISSUE TITLE
Many to Many Tagging

### ISSUE THREAD

**Issue by shakee93** [rtconner/laravel-tagging#109]
I have gone through the documentation. coudnt find a way to tag on a many to many relationship.. here is the scenario. i have `User` table and `Social Media` Table. 1 User can have many Social Medias and a Social Media can have many Users.

![image](https://cloud.githubusercontent.com/assets/14835725/17784830/a3bc8392-659b-11e6-8836-f88fad6080fd.png)

It doesnt work. i have tried several methods. i can add on Social Media or on a User separately. is there any work around for this ?

**Comment by luqmanrom** [comment]
Can you include the model for Social Media?

**Comment by shakee93** [comment]
sorry i just missed this apart. here is my model.
![image](https://cloud.githubusercontent.com/assets/14835725/20668783/9782f2fa-b596-11e6-9cc9-c6884dfa344d.png)

what am i supposed to implement this ?
