### ISSUE TITLE
Error with pluck

### ISSUE THREAD

**Issue by devfelipereis** [rtconner/laravel-tagging#114]
I'm using Laravel 5.1.43 and when I try to use Event::withAnyTag I got this

> Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in..........

I did a debug and see that plunk is returning a string and not an array. I don't undertand why this is happening cause I have the same project in production and there is all working fine. 
 
I'm confused Oo.. Someone can give me some information about this? Thank you!

Edit

In my last test I'm using the latest verson of this package and this is using plunk where I got the error.

Checking the same file in my production server, I see that there the method is using "lists"... I fixed the issue but other people may have the same if running the last version of this package.

**Comment by menkaff** [comment]
i have the same issue

**Comment by devfelipereis** [comment]
I updated my composer.json with:

> "rtconner/laravel-tagging": "dev-laravel-5#214f604ce3da4427b7522a1f50e36658da018572"

It works but I don't have the latest changes.

**Comment by rtconner** [comment]
This commit:
https://github.com/rtconner/laravel-tagging/commit/1691c39e4eab5d66f18bacb83e57df1412e72e9e#diff-5e9f043ae2abfc74b57b29be0a34a24b

I'm told L5.2 to L5.3 changes lists() to pluck()

**Comment by rtconner** [comment]
For L5.1 and L5.2 I would probably just use `composer require rtconner/laravel-tagging "~2.1"`

.. and use ~2.2 for L5.3
