### ISSUE TITLE
lowercase tag names?

### ISSUE THREAD

**Issue by clin407** [rtconner/laravel-tagging#121]
Is it possible to make it so tag names are all lowercase? Since I'm allowing user input, I just want to make it so it looks more consistent.

**Comment by rtconner** [comment]
in the config file (tagging.php) you can specify any normalizer or displayer method that you want.

**Comment by tanshiqi** [comment]
How to return the tag name without any change? I cannot use 'displayer' => '', in config file.
Should I create an useless function? Just like:
function noChange($a) {return $a}

**Comment by rtconner** [comment]
Yeah you would have to have a function that does nothing like your noChange example.

**Comment by tanshiqi** [comment]
OK, I see. Thanks.

**Comment by ferrarafer** [comment]
> How to return the tag name without any change? It seems no effect by setting 'displayer' => '', in config file.
> Should I create an useless function? Just like:
> function noChange($a) {return $a}

You don't need to create the function for that. You can use the value function like this:

`'normalizer'   =>   'value',`

https://laravel.com/docs/5.5/helpers#method-value

> The value function returns the value it is given.
