### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::tag()

### ISSUE THREAD

**Issue by jigsawsoul** [rtconner/laravel-tagging#128]
Hi,

Following this tutorial but I have the error `Call to undefined method Illuminate\Database\Query\Builder::tag()` 

I have run the migrations, added the service provider, and the vendor file.

```
use Conner\Tagging\Taggable;

class AdminJobController extends Controller
{
	use Taggable;
```

```
$job = Jobs::create($request->all());
$job->tag($request->input('categories'));
```

Any ideas

**Comment by akiyamaSM** [comment]
@jigsawsoul the Job Model should have the Taggable trait and not the controller ;)
