### ISSUE TITLE
1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by francoism90** [rtconner/laravel-tagging#129]
EDIT: Solved!

Edit your ```/etc/mysql/my.cfg``` and add the following:
```
[mysqld]
..

# default character set and collation
collation-server = utf8mb4_unicode_ci
character-set-server = utf8mb4

# utf8mb4 long key index
innodb_large_prefix = 1
innodb_file_format = barracuda
innodb_file_format_max = barracuda
innodb_file_per_table = 1

[mysql]
default-character-set=utf8mb4
```

With Laravel 5.4 the database scheme utf8mb4 is used by default, however it may not be enabled on the MariaDB at default.

See http://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified for all needed steps, thanks @scorer!

**Comment by acidjazz** [comment]
@francoism90 I think we should re-open this, there are lots of situations where we don't have access to this kind of stuff, aka Aurora.

**Comment by rtconner** [comment]
So just truncate the tag after a certain number of characters

**Comment by acidjazz** [comment]
Well I think we should at least add to the documentation that if this comes up they'll need to add

```php
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```

to their `AppServiceProvider.php`
