### ISSUE TITLE
[Feature request]: Don't capitalise every word

### ISSUE THREAD

**Issue by jamesmorrish** [rtconner/laravel-tagging#130]
Firstly thanks for the package, installed and working no problems and exactly what I need.

However if I enter a tag like "Foo bar", it capitalises both words to "Foo Bar". Please can you provide a config option to stop this from happening ?

**Comment by rtconner** [comment]
There is a configuration option for this. See https://github.com/rtconner/laravel-tagging/blob/laravel-5/config/tagging.php
