### ISSUE TITLE
 existingTags() issue

### ISSUE THREAD

**Issue by amin101** [rtconner/laravel-tagging#131]
I'm trying to get all tags related to posts have confirmed . so i run this line:
` $tags = Post::where('confirm',1)->existingTags();`

but i run in to this error: 

> Call to undefined method Illuminate\Database\Query\Builder::existingTags()

how can i get all tages related to posts that have been confirmed?

**Comment by rtconner** [comment]
because you need `Post::where('confirm',1)->first()`
