### ISSUE TITLE
Tags are not displayed if tagged model is on not the default DB connection

### ISSUE THREAD

**Issue by UnrulyNatives** [rtconner/laravel-tagging#136]
I have this scenario:
1. My model which I want to tag is on a secondary connection `protected $connection = '2ndconnection';`, and the tags are on the default connection `protected $connection = 'mysql';`

2. In this situation the tags are assigned properly when creating a model 
    $tgs = Input::get('Tags', []);
    $object->retag($tgs);

they can also be affected by edit and methods such as `retag'.

But in the same setting there is a problem: they cannot be displayed with `$article->tags`.

**Solution:**
I had to manually add
`protected $connection = 'mysql';`
to two models in `\vendor\rtconner\laravel-tagging\src\Model\`

Please add the lines to your code in the two model files.

**Comment by rtconner** [comment]
There is a connection settings in the config.
https://github.com/rtconner/laravel-tagging/blob/laravel-5/config/tagging.php

Does that meet your needs?
