### ISSUE TITLE
Untag question 

### ISSUE THREAD

**Issue by chloealee** [rtconner/laravel-tagging#139]
Hello, 

I'm using this laravel-tagging for the first time and love it so far! I've noticed that when I use `untag` (e.g. `$post->untag($tag);`), it doesn't remove it from the `tagging_tagged` table. Is it supposed to? 

Thanks!

**Comment by haheute** [comment]
Here it removes from `tagging_tagged`. 
There is a configuration option in `config/tagging.php` : `'delete_unused_tags'=>true` for removing from `tagging_tags` table.  Perhaps you mean this(?)

**Comment by chloealee** [comment]
thanks for getting back to me so quickly, @haheute ! 

If I use the `untag` function to remove a tag from a post, I want it to be deleted not only from the `tagged` array on the post, but also in the `tagging_tagged` table, not the `tagging_tags` table. Is there a way to do this currently?

**Comment by rtconner** [comment]
Change `delete_unused_tags`  to false.

**Comment by chloealee** [comment]
@rtconner that didn't seem to work :-/

**Comment by chloealee** [comment]
@rtconner when using the `untag` function, is it supposed to remove the record from the `tagging_tagged` table?

**Comment by rtconner** [comment]
Yep.

**Comment by chloealee** [comment]
Okay, thanks!
