### ISSUE TITLE
Error when used with Observers

### ISSUE THREAD

**Issue by rods** [rtconner/laravel-tagging#140]
Lumen 5.3.
Throws Target [Conner\Tagging\Contracts\TaggingUtility] is not instantiable. When Model is registered as an Observer

```
class EventServiceProvider extends ServiceProvider {
public function boot()
    {
        parent::boot();
        Posts::observe(PostsObserver::class);
    }
}
```

```
Class PostObserver {

public function created(Posts $post)
    {
}
}
```

```
class Posts extends Model
{
	use SoftDeletes;

    use Taggable;
}
```

**Comment by rods** [comment]
anyone on this?!

**Comment by rtconner** [comment]
I haven't had any time. If you resolve it please make a pull request.

**Comment by dhilowitz** [comment]
@rods Were you ever able to figure this out?

**Comment by rods** [comment]
@dhilowitz Hi...nop! Since this project is dead i prefered to code a small lib to our needs.

**Comment by mian3010** [comment]
I also had this problem. It turned out to be a matter of ordering. I registered the observers in a ServiceProvider, that was referenced before the ServiceProvider from this module. Swapping the order made it work.

**Comment by prog-24** [comment]
Make your provider that boots the observer come last. In most cases, that is the EventServiceProvider
