### ISSUE TITLE
Why there are duplicate columns (tag_name,tag_slug) in both  tables ?

### ISSUE THREAD

**Issue by Younesi** [rtconner/laravel-tagging#142]
Hi, I've checked Laravel's documentation for [**Many To Many Polymorphic Relations**](https://laravel.com/docs/5.4/eloquent-relationships#many-to-many-polymorphic-relations) and I wonder why you are not following the same pattern for tables!?
instead of a **tag_id** in **tagging_tagged** table  and  accessing tag's name and slug in tagging_tags table **by tag_id** field  ,  you  have **tag_name** and **tag_slug** fields in both tables which  sounds duplication. Right ?

**Comment by rtconner** [comment]
Tags table stores the count summary data. tagging_tagged stores the actual relation. Could probably adjust it how you are asking, but I'm not sure it would be an improvement at all. Is there some suggestion of why it would be better to only have one table?

**Comment by rtconner** [comment]
Closing this as a duplicate see : https://github.com/rtconner/laravel-tagging/issues/94
