### ISSUE TITLE
Adding column to tagging_tagged table

### ISSUE THREAD

**Issue by nicolas-t** [rtconner/laravel-tagging#145]
Hello 

I'd like to add some columns to the table `tagging_tagged` to store extra informations about a tag.
For example the source of the tag : if it has been typed by the user, or generated by an external tagging api like [google vision](https://cloud.google.com/vision/)

Would you add columns to the table `tagging_tagged` ? Or create another related table for the extra informations ?
How would you do it?
Do you think there is a better way than almost rewriting all the `tag()`, `retag()`, `addTag()` ,... functions in  `Taggable` trait ? 

All advices are welcome.

Thanks

**Comment by rtconner** [comment]
I dunno, that seems rough. I would probably add my own migrations and override the TaggingUtility (see the docs)
