### ISSUE TITLE
[question] get all items from model without any tag

### ISSUE THREAD

**Issue by pckz** [rtconner/laravel-tagging#146]
Hello!
As the title says, I need to get all items with at least one tag setted

I'm making a UI to set quickly tags to all Posts without any tags, and I didn't find any help to this case in Usage Examples

Thanks

**Comment by rtconner** [comment]
I'm going to shut this project down. You should look at using a different tag library, there are several others.

**Comment by rtconner** [comment]
Do not have a method to do this. You would have to write your own method. Feel free to make a PR back if you solve this.

**Comment by intranets-talk** [comment]
Probably better ways to do it but.. :

```
$tags = Article::existingTags()->pluck('name')->toJson();
$untagged = Article::withoutTags($tags)->get();
dd($untagged);
```
