### ISSUE TITLE
Why is "rtconner/laravel-tagging" abandoned?

### ISSUE THREAD

**Issue by b00f** [rtconner/laravel-tagging#147]
Updating via composer showed me this message:

`Package rtconner/laravel-tagging is abandoned, you should avoid using it. Use spatie/laravel-tags instead.`
Is rtconner/laravel-tagging is deprecated or moved?

**Comment by ryanicle** [comment]
I've got the same message. I'd like to know too.

**Comment by rtconner** [comment]
I don't really want to maintain this code anymore. I haven't had the time to do it very well.

**Comment by rtconner** [comment]
I mean I'm not going to delete this code base or anything. But I'm don't anticipate doing any updates.

Even with PR's, I've had a few PR's that I didn't put the time in to review throuroughly and then the PR broke a bunch of things when I merged it.

**Comment by schonhose** [comment]
Does someone who migrated from this excellent package towards the package from spatie/laravel-tags have a migration guide?

Is it easy to migrate existing tags from this package to the one from Spatie?

**Comment by m-o-s-t-a-f-a** [comment]
I wanted to do but I dropped it. since it has no features as this package have. still using same

**Comment by christianarevalo** [comment]
The problem with Spatie tags is that it stores the tags in JSON format to support I18n (`name` and `slug`columns) i.e. `{"en": "food"}`. Thus it makes it hard to be able to search and sort (e.g. sort tags in SQL by `name`).

**Comment by schonhose** [comment]
Right, so we would be better off if we stick with the deprecated package?

**Comment by OlexandrPopov** [comment]
> I'm going to shut this project down. You should look at using a different tag library, there are several others.

@rtconner Could you add a note to the readme?

**Comment by JDias** [comment]
I was to use this package (as it has tagGroup, wich for me is an important feature), but artisan:publish is not working. so i cant even start, and now i noticed it is abandoned! :(

**Comment by wilbyang** [comment]
Do you guys find any alternatives?

**Comment by OlexandrPopov** [comment]
@wilbyang check this https://github.com/cviebrock/eloquent-taggable

**Comment by leabdalla** [comment]
@JDias same here. Solved by manually adding service provider to `app/config.php` as readme describes. After that, artisan command will publish files normally.

**Comment by JDias** [comment]
Thanks for that @leabdalla !

hi @wilbyang @OlexandrPopov , i was "using" https://github.com/spatie/laravel-tags 

it seems that "type" is kind of "group", but i didnt test it much.

(in plain php i used to have a polimorphic tag setup, so i could tag anything with any "annotation".
i need to test further, mostly all these packages are more robust than my plain php solution, but im not sure if i will be able to have the same results. im in the process of converting my old app to laravel, and soon to vue/nuxt, but im still learning, in one hand im loving laravel/vue land, in other hand i was used to do my stuff and just work.)
