### ISSUE TITLE
3 tags + retag = 24 requests to the database.

### ISSUE THREAD

**Issue by DmitrySkibitsky** [rtconner/laravel-tagging#150]
```php
//model
protected function reTags($id) {
        $model = Visa::find($id);
        $model->retag(request()->get('tags'));
        $model->save();
}

//controller
 Visa::updateModel($image_id);
 Visa::reTags($request->id);
```
![deepinscreenshot_ - _20180503214746](https://user-images.githubusercontent.com/20288556/39596625-a14867aa-4f1b-11e8-80ec-c963dc9be1d1.png)

This is normal?

**Comment by rtconner** [comment]
I've reduced this a lot by disabled the auto delete empty tags config by dafault.
