### ISSUE TITLE
Tag first letter capital

### ISSUE THREAD

**Issue by virumandaliya** [rtconner/laravel-tagging#151]
Tag first letter becomes capital even I enter in small letters.

I want tags save as it is in database. if enter capital than save tag as capital in db. if enter small than save tag as small in db.

Can you please help me out for this?

**Comment by rtconner** [comment]
There is a config.php file you can adjust this setting

**Comment by virumandaliya** [comment]
Thank you for quick response.

I have checked config file but I could not find settings related to first letter capital.

Can you please point out where actually I have to make the changes?

**Comment by virumandaliya** [comment]
hello,

any guidance please on above point?

**Comment by rtconner** [comment]
Look at this file
https://github.com/rtconner/laravel-tagging/blob/laravel-5/config/tagging.php

You have two options, normalizer and displayer. You can modify either of
those configs. Normalize is before write to database and displayer is used
for front end display.

**Comment by ferrarafer** [comment]
Hi Rob, first of all, thanks for sharing this great package. I've been using it for a while.

I understand what you say to @virumandaliya, but when trying to modify the normalization, I realize that the function applies to both, name and slug, and I really think they are two different things.

Suppose that I want the names of the tags to be saved as they are written, but that the slug be saved as a typical slug, in lowercase and without spaces, I cannot do that. Any advice?

Example:
- tag_name: Carlos III
- tag_slug: carlos-iii

**Comment by warmwhisky** [comment]
I'm still confused on how you get it to not change your tags?

I have commented out both normalizer and displayer but I still get tags in the taging_tags table that are not in my model therefore it breaks some of my pages.

**Comment by warmwhisky** [comment]
Yep, confirmed I have no way of stopping it change my tags. I didn't realise it was doing this until I fully integrated it to my system and then had a product come back in stock "Gin and Tonic". sent out 50 back in stock emails only to get 500 server errors because the tags is exactly "Gin and Tonic" and NOT "Gin And Tonic"

With no direction on how you stop it changing tags, but to just look in config I am stuck with 500 errors.

**Comment by rtconner** [comment]
Don't have a config to turn off normalization, but you could just write a function that does nothing and set it as the displayer...

```
function do_nothing($str) { return $str; }
```

```
'displayer' => '\do_nothing',
```

I could see how this could be a desired config, I'll try to add it but won't be this week.
