### ISSUE TITLE
Error: tagSlugs must return a relationship instance

### ISSUE THREAD

**Issue by JaromirKapitan** [rtconner/laravel-tagging#152]
(1/1) LogicException
App\Dokument\Dokument::tagSlugs must return a relationship instance.

Taggable.php

	public function tagSlugs()
	{
		return $this->tagged->map(function($item){
			return $item->tag_slug;
		})->toArray();
	}

Method has to return relationship not array. Can you rename this method to getTagSlugsAttribute, please?
Thank you.

**Comment by rtconner** [comment]
Interesting. You are using tagSlugs as an attribute and not a method. I had intended you would always do `$model->tagSlugs()`, not `$stub->tagSlugs`
