### ISSUE TITLE
getting articles that it's tags belong to a group

### ISSUE THREAD

**Issue by Xoshbin** [rtconner/laravel-tagging#157]
Hi, Is there any method to grab all the articles that their tags belong to a group? something like below:

Article::withAnyGroup('Gardening');

**Comment by rtconner** [comment]
Don't have that feature at this time. Sorry. I think you would just do a has many through relation.

**Comment by rtconner** [comment]
Closing this as duplicate of https://github.com/rtconner/laravel-tagging/issues/110

That is a complex query as it turns out.

**Comment by Xoshbin** [comment]
I could manage it that way. 
`$posts = Post::withAnyTag(\Conner\Tagging\Model\Tag::inGroup($tagGroupName)->get()->pluck('name')->toArray())->get();`
I know it's kinda slow but it's working for me and I need it.

**Comment by Xoshbin** [comment]
As the project grows, this [method](https://github.com/rtconner/laravel-tagging/issues/157#issuecomment-474705739) is getting slower and slower, So I was asking if anyone knows any other way better than that. I would appreciate it.

`$posts = Post::withAnyTag(\Conner\Tagging\Model\Tag::inGroup($tagGroupName)->get()->pluck('name')->toArray())->get();`
