### ISSUE TITLE
Publishing  not work

### ISSUE THREAD

**Issue by macagoraga** [rtconner/laravel-tagging#158]
After publishing config and migrations are not copied.

**Comment by cbk4092** [comment]
https://laravel.com/docs/5.7/packages#package-discovery

**Comment by yamenarahman** [comment]
Package is not discovered!

**Comment by rtconner** [comment]
@yamenarahman I noticed I had not updated the readme. You need to use version 3 or higher.

`composer require rtconner/laravel-tagging "~3.1"`

**Comment by rtconner** [comment]
This looks to be completely resolved in version 3.0 and higher. Thank you.
