### ISSUE TITLE
command GenerateTagGroup cannot have an empty name

### ISSUE THREAD

**Issue by tdchien** [rtconner/laravel-tagging#166]
Hello @rtconner 
When run php artisan, I got a error message : [LogicException]
> The command defined in "Conner\Tagging\Console\Commands\GenerateTagGroup" cannot have an empty name.

It's seen a problem because laravel version I'm using is 5.0. And property $signature is not exist
> protected $signature = 'tagging:create-group {group_name}';
So should be use $name for command name ?

**Comment by rtconner** [comment]
Ok this should be resolved in v3.2.0
