### ISSUE TITLE
This is a strange bug, but the ID of taggable is lost upon query.

### ISSUE THREAD

**Issue by nickolasnikolic** [rtconner/laravel-tagging#167]
This is a strange bug, but the ID of taggable is lost upon query. Need any help?

**Comment by rtconner** [comment]
Any further details to reproduce this? I would like to fix it.

**Comment by rtconner** [comment]
I cannot figure what this bug is, no reproduce it. Closing this ticket. Please re-open if you are able to help me reproduce it, or give further detail.
