### ISSUE TITLE
TagGroup slug inconsistency

### ISSUE THREAD

**Issue by JoeyStacks** [rtconner/laravel-tagging#169]
Hey so upon creating a tag group using the artisan command the group is created using underscores from the taggingUtility::slug. However regular record creation will create a group using dashes because the mutator for setting the name is using Str::slug.

This is problematic since the tag setGroup method isn't able to find tagGroups with dashes in the slug. Results in Exception (No Tag Group found).

How have you been able to get around this? Any suggestions on creating/updating tag groups?

**Comment by rtconner** [comment]
Thank you for the report, this has been resolved in v3.2.0
