### ISSUE TITLE
insert error

### ISSUE THREAD

**Issue by sedehi** [rtconner/laravel-tagging#17]
I can not add tag Because this error was displayed

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'taggable_id' cannot be null (SQL: insert into `tagging_tagged` (`tag_name`, `tag_slug`, `taggable_type`, `taggable_id`) values (Navid, navid, Post, ))

Sorry for my bad English

**Comment by Tukizz** [comment]
i got same issue, any update or any solution to fix this? thanks

**Comment by rtconner** [comment]
tell me how to reproduce it

**Comment by Tukizz** [comment]
> tell me how to reproduce it

in my case i use Lumen 8

when i create new data like this structure
```php
$data = new Data;
$data->name = $request->name;
$data->tag($tags);
$data->save();
```
it's throw error like @sedehi tell

but if i do like this
```php
$data = new Data;
$data->name = $request->name;
$data->save();
$data->tag($tags);
```
it's working 
@rtconner

**Comment by rtconner** [comment]
I see. I feel like the best I'll be able to do is throw a more informative exception. There is no way to save a tag for a non-created model record.
