### ISSUE TITLE
v3.2.1 - class '\Conner\Tagging\Util' not found

### ISSUE THREAD

**Issue by hennell-git** [rtconner/laravel-tagging#171]
Composer updated and got the latest version of this installed on a cloned repo. It immediately broke tests and tagging and just generally everything everywhere 😉 because of the following error:

```
ErrorException: call_user_func() expects parameter 1 to be a valid callback, class '\Conner\Tagging\Util' not found

[..]/vendor/rtconner/laravel-tagging/src/TaggingUtility.php:49
```

Was trying to work out if this is related to settings in the published config\tagging, but it looks like that still references `'\Conner\Tagging\Util'` so not really sure where the issue lies.

Going back to version 3.1.1 got everything working again, so assume it must be something in 3.2.

**Comment by rtconner** [comment]
Thanks for the report I’ll look into this tonight. I did remove that Util
class, but maybe I missed something.

**Comment by rtconner** [comment]
Yeah this was a bug, very sorry. I have a fix will release in a few hours.

**Comment by rtconner** [comment]
Release v3.2.2  again, thanks for the report!
