### ISSUE TITLE
Multiple definition exists for TestCase in IDE

### ISSUE THREAD

**Issue by hasnatbabur** [rtconner/laravel-tagging#173]
Thanks a lot for the awesome tool.

Is it possible to change the test namespace in you package folder? When I am writing tests my IDE complains that TestCase has multiple definition. I feel it is not a big issue but a simple fix might help. Thanks.

![Capture](https://user-images.githubusercontent.com/7908425/62485207-ea6a4800-b7dd-11e9-94a1-fd5f443d60ea.PNG)

**Comment by rtconner** [comment]
How do other libraries fix this?

**Comment by hasnatbabur** [comment]
@rtconner Please have a look in the image below. Some others using a namespace in their all php files. Thanks

![testfix](https://user-images.githubusercontent.com/7908425/62838682-7b8b6400-bca1-11e9-95c9-aa1093326e9c.PNG)

**Comment by rtconner** [comment]
Fixed in v3.2.3
