### ISSUE TITLE
Can you provide short description field as optional feature for tags? Thanks

### ISSUE THREAD

**Issue by hasnatbabur** [rtconner/laravel-tagging#174]

**Comment by rtconner** [comment]
Hrm. Would have to go on the `tags` table. But yeah I think this is workable.

**Comment by hasnatbabur** [comment]
@rtconner Hi, would you please take a look at this? This is very useful feature and we are waiting highly.  Thanks

**Comment by rtconner** [comment]
this is resolved by mateusjunges  in version 4.0.1
