### ISSUE TITLE
Enhance: Limit or slice maximum allowed number of tags during assigning

### ISSUE THREAD

**Issue by hasnatbabur** [rtconner/laravel-tagging#176]

**Comment by rtconner** [comment]
Wow interesting. I never thought people would tag with 1000's of tags at one time. Is that what you are doing?

**Comment by hasnatbabur** [comment]
Actually not. But a feature request to set limit such as max 3 tags allowed out of the box. Please ignore. Thanks

**Comment by rtconner** [comment]
Oh like a config value?

**Comment by hasnatbabur** [comment]
@rtconner When we extract tag names from string or collection then limit those total tag number to say 3. We will have a helper chain function like ->limit() before attaching tags to Posts. We can have also a default max value in config file.

It is just an enhancement thought from me. I saw often some website only allows max 3 or five tags.

Thanks again.

**Comment by rtconner** [comment]
For behavior, should it throw an exception if you go over the limit, or should it just only add the 3 values?

**Comment by hasnatbabur** [comment]
@rtconner Thanks for reply. Sorry I was away. Ideally if if one do not set limit value in config file or run time then let's add as much as given tags. But limit if valid limit (integer) value is set. It will be more featurefull this way I think. Thanks again.
