### ISSUE TITLE
Tags tables - Database normalization issue

### ISSUE THREAD

**Issue by hasnatbabur** [rtconner/laravel-tagging#177]
Hi, thanks for the library.

On table 'tagging_tags' we have 'tag slug' and 'tag name' columns. But on table 'tagging_tagged' we also have 'tag slug' and 'tag name' columns.

The question is can not we just use tag name and slug from one table only? Using same things (columns) twice in two tables does not violet database normalization rule?

Thanks

**Comment by rtconner** [comment]
This had to be done. I didn't like it either and had the same thoughts as you. But it was the only way to ensure data integrity.
