### ISSUE TITLE
PHPdoc scope methods

### ISSUE THREAD

**Issue by Firtzberg** [rtconner/laravel-tagging#179]
The PHPdoc methods for scopes (e.g. withAllTags) are useless when written down in the trait, since a trait cannot be typehinted. Those should be moved to the contract.

**Comment by rtconner** [comment]
Which editor is this? PHPStorm recognized the trait methods and uses them and gives full method hinting.

**Comment by rtconner** [comment]
Re-open if you can help me reproduce this.
