### ISSUE TITLE
tag_slug not supported on RTL languages

### ISSUE THREAD

**Issue by mohammad-salehnia** [rtconner/laravel-tagging#181]
Hi there 

I'm using this package in my Laravel project (version 6) but tag_slug is not working correctly in RTL languages like Persian and Arabic.

Please check this issue.
Thanks 
![test](https://user-images.githubusercontent.com/12606608/72989565-bde5cf00-3e03-11ea-9465-f9c6a0d2503a.png)

**Comment by hosseinjarrahi** [comment]
you can replace your function to support rtl langs in config

**Comment by rtconner** [comment]
@mohammad-salehnia there is a config option to replace the slug function.

See `normalizer` - https://github.com/rtconner/laravel-tagging/blob/laravel-7/config/tagging.php
