### ISSUE TITLE
Error SQL insert taggable_id

### ISSUE THREAD

**Issue by mor619dx** [rtconner/laravel-tagging#19]
Hi,
I'm having problem using the package (tried master & version 4), when I call tag function I get this error:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'taggable_id' cannot be null (SQL: insert into `tagging_tagged` (`tag_name`, `tag_slug`, `taggable_type`, `taggable_id`) values (Gardening All Day Long, gardening-all-day-long, Article, )) 

it seems taggable_id is not entered and it's define in the db not to be NULL. 
I'm using laravel 4.2 latest.

Edit:
Well I found the problem - I needed to save the Article to the DB before calling tag function (which is reasonable because we need the ID to save as a reference)

**Comment by grgituser** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'taggable_id' cannot be null (SQL: insert into `tagging_tagged` (`tag_name`, `tag_slug`, `taggable_type`, `taggable_id`) values (Ok, ok, SageWolf\Post, ))

can anyone solve ths issue

**Comment by Yarandi** [comment]
@grgituser 
You have to save the model first then set tags and then save again.

**Comment by AlexMalikov94** [comment]
There another option you can just use ```Model::find(1)```. You just pass id your id not create a new model just passing IDs
