### ISSUE TITLE
Multiple database issue

### ISSUE THREAD

**Issue by semprul57** [rtconner/laravel-tagging#193]
Thank you for creating this project, it's make the project easier to put tags on my project

I think i found a bug when inserting tags on multiple database on same codebase, i've put `use \Conner\Tagging\Taggable;` in every model but the tags are stored in only one database with different `taggable_type`.

I've tried to hard coded the ` $this->connection` on `\Conner\Tagging\Model\Tag` to un-inserted database and it's work, i guess the problem is how to make `$this->connection = config('tagging.connection')` dynamically based on parent Model but i still can't find the solution for this.

The expected result are stored in separate database that already specified in `protected $connection` part in Model.

I hope this information can improve your project.

Thank You

**Comment by rtconner** [comment]
This is probable impossible due to issues with cross table joins
