### ISSUE TITLE
Using with UUID not working

### ISSUE THREAD

**Issue by hybrid1969** [rtconner/laravel-tagging#194]
Hi

All my tables use UUID id fields instead of incremental and applying and retrieving tags appears to work all ok.

However withAnyTag/ withAllTags/ withoutTags do not seem to work.
Do I need to change something to account for the UUID fields?

Thanks

**Comment by rtconner** [comment]
set the config for primary keys

https://github.com/rtconner/laravel-tagging/blob/laravel-8/config/tagging.php

**Comment by hybrid1969** [comment]
didnt even notice that, thanks for the quick response and will try asap.
