### ISSUE TITLE
How to delete old tags when Article updated 

### ISSUE THREAD

**Issue by KhurshidYakubov** [rtconner/laravel-tagging#197]
Hello there, 

When I update articles it is adding new tag tags for this article by not removing old ones. 

For example,  I have tags for Article 1 as follow: **github** , **stackoverflow** , **microsoft** . 
Now I want to edit these tags by removing them and setting new ones( **leetcode** , **hackerrank**) . so when I update it has to show  **leetcode** , **hackerrank**. But it is showing  **leetcode** , **hackerrank** , **github** , **stackoverflow** , **microsoft**

my update function looks like this:

![image](https://user-images.githubusercontent.com/40025822/103282957-18ff4900-49f9-11eb-92b4-0c7ef8757e44.png)

How can deal with this ?

**Comment by amphetkid** [comment]
$post->untag();
$post->tag($tags);
$post->save;

**Comment by KhurshidYakubov** [comment]
@amphetkid thank you very much :)
