### ISSUE TITLE
how to delete tag from database?

### ISSUE THREAD

**Issue by kossak31** [rtconner/laravel-tagging#199]
hello,
i am trying to delete tags from database.
i use this:
```
$article->retag(array('Fruit', 'Fish'));
$article->untag();
```
but tags still in database.... 

thanks for the info

**Comment by rtconner** [comment]
Delete the actual tags or delete the tag relations?

**Comment by kossak31** [comment]
i what to delete the actual tags from database erase them

**Comment by rtconner** [comment]
use the Tag model. https://laravel.com/docs/8.x/eloquent#deleting-models
