### ISSUE TITLE
Why the tag->slug only affect the changes when the tag->name is changed?

### ISSUE THREAD

**Issue by PR4M** [rtconner/laravel-tagging#201]
Is there any other way to solve this issue? Because I don't always need the tag->slug to follow the name convention rule e.g: 
Laravel Framework -> laravel-framework, sometimes we want: Laravel Framework -> laravel.

**Comment by rtconner** [comment]
you can override the 'normalizer' config if you want to change how slugs are generated.

https://github.com/rtconner/laravel-tagging/blob/laravel-8/config/tagging.php
