### ISSUE TITLE
soft delete

### ISSUE THREAD

**Issue by mohammadremoradi** [rtconner/laravel-tagging#202]
im using soft delete for articles 

when i restore the articles all the tags is deleted 

can you help me with that please

**Comment by casperwilkes** [comment]
Check the documentation. 
There is a config value:
`config/tagging.php`: `'untag_on_delete' => true,`

**Comment by mohammadremoradi** [comment]
Hello bro

It is true but when a article will be a soft delete and I return it all the articles tag will be delete

**Comment by rtconner** [comment]
The setting from  @casperwilkes is the only setting. If you have that set to false already then the tags would not be deleted when you delete your model.
