### ISSUE TITLE
UUID - When use UUID versus ID = int

### ISSUE THREAD

**Issue by jordivela007** [rtconner/laravel-tagging#211]
When I use UUID for my models, it's necessary to modify the database schema to support this functionality.

`taggable_id` char(36) NOT NULL COMMENT 'Taggable_Id',

Seems no use the option in the config file 'primary_keys_type' => 'string', 

How to create a migration again?

**Comment by rtconner** [comment]
See the config option here - https://github.com/rtconner/laravel-tagging/blob/master/config/tagging.php#L6

If you set it before running migrations then it is used .. 

https://github.com/rtconner/laravel-tagging/blob/master/migrations/2014_01_07_073615_create_tagged_table.php#L11

**Comment by rtconner** [comment]
See also laravel migration docs https://laravel.com/docs/10.x/migrations
