### ISSUE TITLE
Add new filter to get only matching tags.

### ISSUE THREAD

**Issue by vikas-ukani** [rtconner/laravel-tagging#212]
Let's say, we have articles, and their tags are **['Gardening', 'Cooking', 'Sharping']** and I want to get only matching results.

example.
Artical table
`name      tags`
`article-1    Gardening,Cooking,Sharping ` 
`article-2    Gardening,Cooking` 

I want a new filter that will return me only selected tags 
example: 
`Artical::withOnlyTags(['Gardening', 'Cooking'])->get()`

This will return only `article-2`.

**Comment by vikas-ukani** [comment]
Hello @rtconner 
Do we have such a method as `withOnlyTags(['Gardening', 'Cooking'])`

**Comment by rtconner** [comment]
https://github.com/rtconner/laravel-tagging/blob/master/docs/usage-examples.md
