### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by hardikaecor** [rtconner/laravel-tagging#25]
How can I use this package in L5?

**Comment by walteranderson** [comment]
This may not be entirely applicable, but I did find this link that discusses a potential workaround for package migrations (if that is still the problem).

http://laravel.io/forum/01-08-2015-package-migrations-not-working-in-laravel-5

**Comment by rtconner** [comment]
Ok I've got this running on L5. Let me know if there are any issues please.

composer require rtconner/laravel-tagging dev-laravel-5
