### ISSUE TITLE
Taxonomy Feature

### ISSUE THREAD

**Issue by UnderlineWords** [rtconner/laravel-tagging#28]
Hi, I'm using this package in my CMS project. Your package is a great solution for tagging and thanks for sharing! I wanna ask you that; are you planning to development a Taxonomy feature as part of your tagging package?

**Comment by rtconner** [comment]
No that I know of. Do you have details of how you think that should work, specifically?

**Comment by UnderlineWords** [comment]
I actually don't know how to work exactly. But i tried couple times with a new taxonomy model (with add, edit, delete actions and terms relation to taxonomy). But i couldn't unfortunately. I'm new about Laravel and i'm still trying to learning. But i would like to share when i find a solution.
