### ISSUE TITLE
Invalid version string "^1.2.2"

### ISSUE THREAD

**Issue by polyesterhat** [rtconner/laravel-tagging#38]
Running `composer require rtconner/laravel-tagging "~1.0.2"` gives an error: 

    [RuntimeException]
    Could not load package classpreloader/classpreloader in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.2.2:  
    Invalid version string "^1.2.2"    

    [UnexpectedValueException]                                                  
    Could not parse version constraint ^1.2.2: Invalid version string "^1.2.2"  

I had been using laravel-tagging with Laravel 4, but upgrading my project to laravel 5 is now impossible since laravel-tagging keeps getting an error. What should I try?

**Comment by rtconner** [comment]
Uh. I don't think this is an issue in my library. I don't use 1.2.2 of anything.

Edit your composer.json and just change whatever the library is to ~1.2.2

**Comment by polyesterhat** [comment]
Thank you.

**Comment by polyesterhat** [comment]
issue was composer itself was out dated. `composer self-update && composer update` fixed issue.

should I be using 

        "rtconner/laravel-tagging": "~1.0.2"
        OR
        "rtconner/laravel-tagging": "dev-master"

in my composer.json?

**Comment by rtconner** [comment]
```
"rtconner/laravel-tagging": "~1.0.2"
```

dev-master will not work at all. if anything dev-laravel-5 will get you bleeding edge updates, but I don't recommend it.
