### ISSUE TITLE
existingTags() not works

### ISSUE THREAD

**Issue by fengys** [rtconner/laravel-tagging#39]
```php
	public static function existingTags() {
		return Tagged::distinct()
			->join('tagging_tags', 'tag_slug', '=', 'tagging_tags.slug')
			->where('taggable_type', '=', get_called_class())
			->orderBy('tag_slug', 'ASC')
			->get(array('tag_slug as slug', 'tag_name as name', 'tagging_tags.count as count'));
	}
```

I'm sure  
get_called_class() get value '\App\Models\Article'
so can not found any record in database 
`'taggable_type'='Article'`

**Comment by dambridge** [comment]
Yep, same. Think the backslashes entered in column are breaking it.

**Comment by rtconner** [comment]
Ok I'll try to get this fixed asap.

**Comment by dambridge** [comment]
Ended up with this, hard-coding the model name in for now:

```
return \DB::table('tagging_tagged')
            ->distinct()
            ->join('tagging_tags', 'tagging_tagged.tag_slug', '=', 'tagging_tags.slug')
            ->where('tagging_tagged.taggable_type', 'like', '%App\\\\MyModel%')
            ->orderBy('tagging_tags.slug')
            ->get();
```

**Comment by rtconner** [comment]
... so far I'm just not able to reproduce this issue at all.

What database are you using? MySQL? Which version of Laravel? Which version of this library?

**Comment by dambridge** [comment]
L5, mysql, "rtconner/laravel-tagging": "~1.0.2"

**Comment by fengys** [comment]
MySQL
Laravel 5
newest version "rtconner/laravel-tagging": "~1.0.2"

**Comment by rtconner** [comment]
I just can't reproduce this at all. I did one upgrade in hopes of fixing  - use laravel getMorphClass() - which is a good update. 

Any chance it fixes your issue? I made version 1.0.3

Otherwise I might need someone to tell me what code to change to fix this, I just have no idea.

**Comment by fengys** [comment]
Updated.
I think it fixed.

there is 'Article' in  database on `taggable_type`
get_called_class() get value '\App\Models\Article' it failed

when

class Article extends \Illuminate\Database\Eloquent\Model {
    use \Conner\Tagging\TaggableTrait;
    protected $morphClass = 'Article';

morphClass() will get correct taggable_type 'Article'

But I think if somebody has not set $morphClass, this fix won't works?

**Comment by rtconner** [comment]
Setting $morphClass is a good idea and works great. I think it's a good way to go here.

Did you have Article with no namespace, and then add a namespace later? I think that's the only explanation is that you renamed the class?

**Comment by fengys** [comment]
It was not works without setting $morphClass

**Comment by rtconner** [comment]
I know. But I think that is ok.

**Comment by fengys** [comment]
Sure. Thanks for you help! I think this issue can be close.

**Comment by rtconner** [comment]
Thanks for the report and working with me.

**Comment by grgituser** [comment]
$article = Post::with('tagged')->first(); // eager load
        dd($article->tagNames());
Returning an empty array.  what wrong ?
Thanks
