### ISSUE TITLE
Bug: required field Name

### ISSUE THREAD

**Issue by forsaken1** [rtconner/laravel-tagging#4]
Error with tagName == "" (if empty string)
![obnoamrwb40](https://cloud.githubusercontent.com/assets/1580566/2875146/e0f5ef18-d40d-11e3-81c5-9eaa24977e76.jpg)

**Comment by acoustep** [comment]
I just came across this issue myself.

I'm using the following to get an array of tags from an input box:

```
$tags = array_map('trim', explode(',', Input::get('tags', [])));
$post->retag($tags);
```

In this situation I would prefer if all tags were removed and no exception was thrown as the user has cleared the input box of all data.

Is there a better solution to do this?
