### ISSUE TITLE
Unable to publish config/migrations.

### ISSUE THREAD

**Issue by kevdotbadger** [rtconner/laravel-tagging#43]
The original path `__DIR__.'/../../../config/tagging.php' => config_path('tagging.php'),` seems to be wrong. I had to change this in my basic setup to `_DIR__.'/../config/tagging.php' => config_path('tagging.php'),`.

**Comment by rtconner** [comment]
Ah I think you are right. This is a bug caused by the move to PSR4. Thanks will fix asap.

**Comment by rtconner** [comment]
Ok fixed in v 1.0.6

**Comment by kevdotbadger** [comment]
Thanks.
