### ISSUE TITLE
Missing tables in database

### ISSUE THREAD

**Issue by elertan** [rtconner/laravel-tagging#45]
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'artotheek5.tagging_tagged' doesn't exist (SQL: select count(*) as aggregate from `tagging_tagged` where `tagging_tagged`.`taggable_id` = 1 and `tagging_tagged`.`taggable_type` = App\News and `tag_slug` = test limit 1)'

I have followed all steps and it seems that I am missing some tables in the database, they don't seem to be added by artisan migrate. Can someone help me to see what I'm doing wrong, thanks.

**Comment by rtconner** [comment]
Did you run 

`php artisan vendor:publish --provider="Conner\Tagging\TaggingServiceProvider"`
then
`php artisan migrate`

**Comment by rtconner** [comment]
Dangit there was a bug in the migration publish. This is what I get for merging pull requests without testing. Shame on me. Anyways fixed (if you run those commands)

**Comment by rtconner** [comment]
Fixed in version 1.0.7

**Comment by elertan** [comment]
Thanks ill test it today

**Comment by elertan** [comment]
It's working perfectly thanks for fixing!
