### ISSUE TITLE
*->tagged returns empty collection

### ISSUE THREAD

**Issue by Ortix92** [rtconner/laravel-tagging#47]
I just upgraded to L5 and I have noticed that the tags stopped working. The database is populated, the model uses the trait, but the tags are not retrieved.

I can provide any information necessary, but I haven no clue how to debug this at the moment. Everything should work.

The class using it extends `Model` instead of `Eloquent` as it used to be in L4

**Comment by Ortix92** [comment]
I figured it out. Since I namespaced my Models, the query now binds the full namespace to the taggable type. In my database it's still the old type, not namespaced. 

In my case this is a problem from my end, however, I can imagine someone changing their application directory and moving their models. Their tags would not work anymore. Dropping the namespace is not an options so I would not know how this could be mitigated. 

Either way, it's just a heads up.

**Comment by rtconner** [comment]
Hrm. Yeam make like a command line script to migrate?

**Comment by Ortix92** [comment]
A CLI migration would indeed do the trick imo
