### ISSUE TITLE
'untag_on_delete' does not delete "everything"

### ISSUE THREAD

**Issue by Cyb0rk** [rtconner/laravel-tagging#48]
Hi there,

I have ```'untag_on_delete' => true,``` in my config/tagging.php

But when I do ```Model::destroy($id);``` my model is destroyed correct. In the table ```tagging_tagged``` it is deleted correctly, but the in the table ```tagging_tags``` there is still a entry with the used tag. Only the ```count``` is set to zero.

Is this how it should work? Or should the row in the ```tagging_tabs``` table also be deleted? And when it is kept: why?

Thanks for your answer.

**Comment by rtconner** [comment]
Interesting. I hadn't thought of that. You think it should delete the Tag also? I assume some people would want the tag left in place.

**Comment by Cyb0rk** [comment]
Yes I do.

Why should the tag left in the database? If it isn't used its just junk. If somebody needs it again it will be created automatically, doesn't it?

But that's just my opinion. You are the developer :).

**Comment by rtconner** [comment]
Ya, probably make it a config option.

**Comment by Cyb0rk** [comment]
Greate Idea! Thanks for your support :+1

**Comment by rtconner** [comment]
I've added the config option 'delete_unused_tags' in version 1.1.0
