### ISSUE TITLE
Call to undefined function Conner\Tagging\database_path()

### ISSUE THREAD

**Issue by jbtbnl** [rtconner/laravel-tagging#49]
I fixed it by reverting https://github.com/rtconner/laravel-tagging/commit/b1778c078f9e3634fc8bdcf4dc3bb38b52c93e2b

**Comment by rtconner** [comment]
hrm. what version of Laravel are you on?

**Comment by rtconner** [comment]
I haven't been able to reproduce this.

**Comment by jbtbnl** [comment]
I'm using Laravel 5.0.33 with PSR-4.

**Comment by rtconner** [comment]
This should be resolved in version 1.1.0
