### ISSUE TITLE
Is there a feature to remove all unused tags?

### ISSUE THREAD

**Issue by ziming** [rtconner/laravel-tagging#51]
Hi, great package here. Is there a feature to remove all unused tags currently or planned?

Something like Tag::removeUnusedTags();

**Comment by rtconner** [comment]
I did plan on building this. So will be added hopefully soon. I just need to sit down and code out a bunch of updates.

**Comment by devmark** [comment]
thanks:)

**Comment by rtconner** [comment]
added config option 'delete_unused_tags' as well as method TaggingUtil::deleteUnusedTags()
