### ISSUE TITLE
Wrong Migrations. config/tagging.php 'primary_keys_type' => 'integer' doesn't work.

### ISSUE THREAD

**Issue by pechatny** [rtconner/laravel-tagging#54]
I'm installing rtconner/laravel-tagging by composer. And "laravel-tagging/migrations/2014_01_07_073615_create_tagged_table.php" looks different than on github.
GitHub version:
		Schema::create('tagging_tagged', function(Blueprint $table) {
			$table->increments('id');
			if(\Config::get('tagging.primary_keys_type') == 'integer') {
				$table->integer('taggable_id')->unsigned()->index();
			} else {
				$table->string('taggable_id', 36)->index();
			}
			$table->string('taggable_type', 255)->index();
			$table->string('tag_name', 255);
			$table->string('tag_slug', 255)->index();
		});

Composer version:
                Schema::create('tagging_tagged', function(Blueprint $table) {
			$table->increments('id');
			$table->string('taggable_id', 36)->index();
			$table->string('taggable_type', 255)->index();
			//$table->morphs('taggable');
			$table->string('tag_name', 255);
			$table->string('tag_slug', 255)->index();
		});

What should I do? Or what shoud you do? ) I would be very thankful if you helped me.

**Comment by rtconner** [comment]
1.0.7 is the latest stable release. You can browse the code here - https://github.com/rtconner/laravel-tagging/tree/1.0.7

**Comment by pechatny** [comment]
I'm just wanted to be able to update with composer automatically, not manually.

**Comment by rtconner** [comment]
Is this what your composer.json file looks like?

```
"rtconner/laravel-tagging" : "~1.0.7"
```

**Comment by pechatny** [comment]
Yes it's looks like this.

**Comment by rtconner** [comment]
Don't copy migrations from github. Delete your migrations and follow the instructions ..

https://github.com/rtconner/laravel-tagging#install-and-then-run-the-migrations

**Comment by pechatny** [comment]
Thanks for answer, I will try one more time lately. Even though I did everything step by step following instructions.

**Comment by pechatny** [comment]
I got the same result.  Please compare tagging/migrations/2014_01_07_073615_create_tagged_table.php on laravel-5 branch and tag 1.0.7

![shot1](https://cloud.githubusercontent.com/assets/3494162/8589981/b1473726-2624-11e5-8210-fad8ccf6a68b.PNG)
![example 1](https://cloud.githubusercontent.com/assets/3494162/8589987/b5350462-2624-11e5-9248-1c0f5c91a627.PNG)
![shot2](https://cloud.githubusercontent.com/assets/3494162/8589988/b6f87e32-2624-11e5-8db7-f06d6c7762a9.PNG)
![example 2](https://cloud.githubusercontent.com/assets/3494162/8589989/b92936ce-2624-11e5-8cde-5bb7e8fbbdb3.PNG)

**Comment by rtconner** [comment]
version 1.1 is released. perhaps delete and reinstall.
