### ISSUE TITLE
Eager loading for tagNames

### ISSUE THREAD

**Issue by greed** [rtconner/laravel-tagging#56]
Hello,

If I am trying to use eager for tagNames. Something like:
$allMedia = Media::with("tagged")->get();
foreach($allMedia as $item) {
    print_r($item->tagNames());
}
but it doesn't work with current implementation in tagNames:
$tagged = $this->tagged()->get(array('tag_name'));

It would if you remove "get" column and just use $this->tagged:
foreach($this->tagged as $tagged) {
    $tagNames[] = $tagged->tag_name;
}

**Comment by rtconner** [comment]
Ah you are right. Good eye.

**Comment by rtconner** [comment]
version 1.1.1

**Comment by greed** [comment]
Hey,

just checked new version. You've fixed this problem for tagSlugs but not tagNames.
Forgot to mention before that both functions has this problem.
Can you please fix tagNames too.

Thanks

**Comment by rtconner** [comment]
I'm sorry about that. That'll teach me to rush on these things.

Fixed in version 1.1.2 now.
