### ISSUE TITLE
Possible to create unattached tags?

### ISSUE THREAD

**Issue by syropian** [rtconner/laravel-tagging#60]
Is this possible? In my app, video clips will have tags attached, but the user should be able to simply create the tags themselves, and then add them to clips at their leisure.

**Comment by younes0** [comment]
Maybe you could simply create Tagging_Tags models to insert these unattached tags ?

**Comment by rtconner** [comment]
I may need more details on what you are expecting. Currently you can do this ..

Set 'delete_unused_tags' to false in config

```php
\Conner\Tagging\Tag::save('name'=>'My Tag', 'slug'=>'my-tag', 'suggest'=>true);
$suggestedTags = \Conner\Tagging\Tag::suggested()->get();
```
Does that fill your needs or is there something more?

**Comment by syropian** [comment]
@rtconner Basically I just want to create a tag that doesn't (immediately) belong to a model. If I simply create an instance of `\Conner\Tagging\Tag` will that work? I wasn't sure if it _needed_ an associated model.

**Comment by rtconner** [comment]
Definitely set 'delete_unused_tags' to false in the config.

You can insert rows into `\Conner\Tagging\Tag` as much as you like sure.

The 'suggest' boolean is just an option if you want to use it. It links to the ::suggested() filter so you can maybe use it to suggest certain tags to users or something.

**Comment by syropian** [comment]
@rtconner Awesome, thanks!
