### ISSUE TITLE
Tags versionning

### ISSUE THREAD

**Issue by younes0** [rtconner/laravel-tagging#61]
In my project, I have an automatic tagger (thanks to machine learning)
Since it's machine driven, humans need to readjust the tagging.
But it's important to keep the human and machine versions so machine can learn over time.

What if this library could allow this:
```php
$model->setTagsVersion('machine');

// TaggedTrait.php
public function setTagsVersion($verison)
{
    $this->tagsVersion = $version;
}

// filter rows based on "version" tagged column 
public function tagged()
{
    $relation = $this->morphMany('Conner\Tagging\Tagged', 'taggable');
    // not sure if $morphMany accepts where chaining method
    return ($this->version) ? $relation->where('version', $this->tagsVersion) : $relation;
}

**Comment by rtconner** [comment]
I don't think I want to add this. It does not seem like a common enough use case to include in the library. 

If you need this feature, you should probably just copy code from this library into your application, and modify it to suite your needs.

**Comment by younes0** [comment]
you're right, thanks for your feedback, I might fork the library to add this feature
