### ISSUE TITLE
Get all tags that belong to a user

### ISSUE THREAD

**Issue by syropian** [rtconner/laravel-tagging#63]
I noticed none of the tag tables have an associated user_id key or anything. What's the best way to fetch all tags that were created by a specific user?

**Comment by rtconner** [comment]
This is not a feature that I want to support with this library. Too much overhead on tracking that.

**Comment by Kyslik** [comment]
I would like to track tags per user as well.
Can you at least point out which methods to override?

**Comment by jasondavis** [comment]
perhaps this could be forked and modified for multi user tagging.  My use case has Bookmark models which need to have all the tagging capabilities this library has but only for the current logged in user so each user has its own set of tags

**Comment by rtconner** [comment]
> perhaps this could be forked and modified for multi user tagging

It's an open source library. You are encouraged to do so.
