### ISSUE TITLE
suggest column

### ISSUE THREAD

**Issue by DesmondPang** [rtconner/laravel-tagging#64]
I found that there is a column called "suggest" column on database table. What is its purpose?

**Comment by rtconner** [comment]
Just a tool for people to use if they wanted to. 
`Tag::suggested()->get()` would return a list of "suggested" tags for whatever purpose you want to use that for.

**Comment by rtconner** [comment]
https://github.com/rtconner/laravel-tagging/blob/laravel-5/docs/suggesting.md
