### ISSUE TITLE
How to override TaggingUtil class?

### ISSUE THREAD

**Issue by DesmondPang** [rtconner/laravel-tagging#65]
I tried to add some customised functions to the TaggingUtil class. How to extend it so that the TaggableTrait class can call the customised TaggingUtil class. What I would like to do is no need to change the anything of your library in vendor folder but allow me to customise the functions. Because I added other columns to the database table.

**Comment by rtconner** [comment]
I have to make some changes, and add an interface. I've wanted to do this anyways, so hopefully over the weekend I can do these.

**Comment by rtconner** [comment]
Version 2.0 is a major upgrade. You'll need to re-install.

https://github.com/rtconner/laravel-tagging/blob/laravel-5/docs/how-to-override-util.md

Let me know how it works for you.

**Comment by rtconner** [comment]
I've added these in version 2.0.

Version 2.0 is a major upgrade. You'll need to fix class names in a few places.

**Comment by DesmondPang** [comment]
Sorry, error occur during vendor publish. Please change the directories of the files. You missed one "/.." for the path.

Should be the following paths:


	public function boot()
	{
		$this->publishes([
			__DIR__.'/../../config/tagging.php' => config_path('tagging.php'),
			__DIR__.'/../../migrations/2014_01_07_073615_create_tagged_table.php' => $this->app->databasePath().('/migrations/2014_01_07_073615_create_tagged_table.php'),
			__DIR__.'/../../migrations/2014_01_07_073615_create_tags_table.php' => $this->app->databasePath().('/migrations/2014_01_07_073615_create_tags_table.php'),
		]);
	}

**Comment by rtconner** [comment]
Ah you are right, I moved that file. Thank you.

**Comment by rtconner** [comment]
Version 2.0.1
