### ISSUE TITLE
Composer\Repository\RepositorySecurityException

### ISSUE THREAD

**Issue by AlexECP** [rtconner/laravel-tagging#66]
Im getting the following error when running **composer require rtconner/laravel-tagging "~2.0."**:

[Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/provider-2014$1a08cb0ca56f3fe73f5b1e9531f2741e1fd1ba5bdbde741c9832ff67ece460a3.json do not match its signature. This should indicate a man-in-the-m
  iddle attack. Try running composer again and report this if you think it is a mistake.

**Comment by rtconner** [comment]
You behind a firewall or proxy of some sort?

**Comment by AlexECP** [comment]
Yeah sorry, this was the first time I had gotten this sort of error, and it seemed you had recently modified the repository, so I thought it was connected, but it had something to do with my ISP.
