### ISSUE TITLE
TaggableTrait not working inside workbench model.

### ISSUE THREAD

**Issue by nonoesp** [rtconner/laravel-tagging#72]
When defining the Article model inside a package of my own, the whole trait seems to be working but there arrays returned—in ```$article->tagNames()```, for instance—are completely empty.

The package I am developing is ```Nonoesp\Writing```, being the model ```Nonoesp\Writing\Article```.

The TaggableTrait is defined inside the Article model as follows:

```
<?php namespace Nonoesp\Writing;

class Article extends \Eloquent {
	use \Illuminate\Database\Eloquent\SoftDeletingTrait;
	use \Conner\Tagging\TaggableTrait;
```

A workaround that works properly is taking the Article model outside the package and using that within the package, but I would like the package to use its own model.

Any ideas of why this is happening? Thanks!

**Comment by rtconner** [comment]
what version of laravel and this library?
didn't they remove workbench from Laravel 5?

**Comment by nonoesp** [comment]
I actually using Laravel 4.2.

**Comment by rtconner** [comment]
If you solve this, please share how you solved it.

**Comment by nonoesp** [comment]
I have reproduced this same problem with a Laravel 5 package, which makes it impossible to use the Taggable Trait in the Article model that ships with my package.

**Comment by nonoesp** [comment]
I am updating my package to Laravel 5.2. The problem (it seems to be) is the Taggable trait isn't working when implementing in a namespace other that the main App's namespace.

**Comment by nonoesp** [comment]
In updating my package to Laravel 5.2 I found this now works — using my own model inside my own namespace.
