### ISSUE TITLE
problem with php artisan migrate:reset

### ISSUE THREAD

**Issue by mitjarobic** [rtconner/laravel-tagging#8]
I get the following error:

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'CreateTagsTable' not found","file":"C:\inetpub\wwwroot\elearning-api\src\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php","line":297}}

**Comment by Cyb0rk** [comment]
Still not fixed:

XXX@XXX:~/XXX$ php artisan migrate:refresh
PHP Fatal error:  Class 'CreateTagsTable' not found in /var/www/clients/client2/web2/XXX.XXX.XXX/rezepte/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 328



  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'CreateTagsTable' not found

Using newest version installed via composer
