### ISSUE TITLE
Moloquent compatibility

### ISSUE THREAD

**Issue by frco9** [rtconner/laravel-tagging#81]
Hello, 

I'm using [Moloquent](https://github.com/jenssegers/laravel-mongodb) with my app, thus each model must extend Moloquent model instead of the Eloquent one. 

Any idea on the best way to achieve that ? 

Thanks

**Comment by rtconner** [comment]
Probably have to adjust the library to allow configure model classes in config.

**Comment by rtconner** [comment]
I have no plans make this library work with Mongo. I would be open to contributions if someone wrote the code for it.
