### ISSUE TITLE
0.5.3 incompatible with Laravel 4 for php 7

### ISSUE THREAD

**Issue by matohavo** [rtconner/laravel-tagging#92]
Hi Rob, I'm testing latest release (0.5.3) on php 7 with Laravel 4, but there seems to be incompatibility as "illuminate/database": ">= 5.0" is used, which causes uninstallable set of packages.

Is there any way around? Or is this release supposed to be working only for L5?
Thanks

**Comment by rtconner** [comment]
That's strange. I must have cut a release from the wrong hash or branch. I'll get a new release out at some point tonight. You could use "dev-laravel-4" in composer if needed for the short term.

**Comment by rtconner** [comment]
Ok sorry about that, new release of 0.5.4 is made.
