### ISSUE TITLE
[question] Table normalization

### ISSUE THREAD

**Issue by FR6** [rtconner/laravel-tagging#94]
Hi @rtconner ,

Out of curiosity, why in your table "tagging_tagged" do you have the fields "tag_name" and "tag_slug" and not just a reference ID (ex.: tag_id) to the tag in the table "tagging_tags"?

It seems to me that your tables aren't properly normalized because the tags information will be duplicated each time content is tagged.

**Comment by devmark** [comment]
https://github.com/rtconner/laravel-tagging/issues/9

take a look

**Comment by FR6** [comment]
Thanks @devmark .

"code was just easier to write as it is now"... yikes.

**Comment by tomschlick** [comment]
Yeah this is scary, and probably the reason for some of the mentioned performance problems... 

If I wrote a PR that migrated everything to a `tag_id` and moved the records accordingly would that be something that would be accepted?

**Comment by rtconner** [comment]
Yep. @tomschlick Thank would be great.

**Comment by tsunamilx** [comment]
Is there any update now?

**Comment by dereksdev** [comment]
Is this dead?

**Comment by rtconner** [comment]
Does anyone use the `count` field on the tags table? That field is the biggest reason for this -- storing the summary. I felt like it would be bulky to calculate the count on the fly.

**Comment by rtconner** [comment]
I'm never going to normalize the tables as described in this request. There are advantages to the current structure (eg the `count` field)

However there are many places where queries could be optimized to work much faster. So I will have to work on that.
