### ISSUE TITLE
Article::with('tag')->first(); is not working 

### ISSUE THREAD

**Issue by rohitpal440** [rtconner/laravel-tagging#96]
when try to execute the following statement
`Article::with('tag')->first(); `
it throws an exception

`BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::tag()'`

**Comment by rtconner** [comment]
Per the documentation : 
```
$article = Article::with('tagged')->first(); // eager load
```

https://github.com/rtconner/laravel-tagging/blob/laravel-5/docs/usage-examples.md
