### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by marianvlad** [rtconner/laravel-tagging#99]
I use this package and I have a tag used by ~9k posts and when I use withAllTags method to get the posts, my website dies.

**Comment by rtconner** [comment]
Any suggestions on what to adjust by chance?

**Comment by markeilander** [comment]
@marianvlad A simple sollution could be caching.

For one of my older projects i've build a caching layer on top of the tagging trait with some events to cleanup the cache when new tags are inserted.

An other option could be to paginate the results returned by withAllTags

**Comment by FutureFutureTo** [comment]
Late to the party here but you should definitely paginate your response.

`$posts = Post::withAllTags(['tag1, tag2])->paginate();`

**Comment by rtconner** [comment]
Use eager loading please.
